language: python
python:
    - 3.6
    - 3.7
    - 3.8
sudo: false
env:
install:
    - pip install .[test]
script:
    - python setup.py --version
    - python setup.py build_py
    - python setup.py sdist
    - python -m pytest
