language: python
python:
    - 2.7
    - 3.5
sudo: false
env:
install:
    - pip install pytest
    - pip install .
script:
    - python setup.py --version
    - python setup.py build_py
    - python setup.py sdist
    - python -m pytest
