# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

# environment variables
environment:
  matrix:
    - PYTHON: "C:\\Miniconda36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_MAJOR: 3
      PYTHON_ARCH: "64"

# scripts that run after cloning repository
install:
  # Ensure python scripts are from right version:
  - 'SET "PATH=%PYTHON%\Scripts;%PYTHON%;%PATH%"'
  # Update install tools:
  - 'python -m pip install --upgrade pip'
  # Install test dpendency
  - 'pip install pytest'
  # Install our package:
  - 'pip install .'

build: off

# to run your custom scripts instead of automatic tests
test_script:
  - 'python setup.py --version'
  - 'python setup.py build_py'
  - 'python setup.py sdist'
  - 'python -m pytest'
