name: CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.6", "3.7", "3.8"]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python_version }}
        architecture: 'x64'

    - name: Install dependencies
      run: pip install .[test]

    - name: Run test
      run: |
        python setup.py --version
        python setup.py build_py
        python setup.py sdist
        python -m pytest
